# Generated by Django 3.2.10 on 2022-01-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_trademark_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademark',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
