# Generated by Django 3.2.10 on 2022-01-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0005_alter_trademark_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='_type',
            field=models.IntegerField(choices=[('exclude', '除外'), ('include', '必須')], default=None),
            preserve_default=False,
        ),
    ]
