# Generated by Django 3.2.10 on 2022-01-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0006_domain__type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
