# Generated by Django 3.2.10 on 2022-01-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0007_alter_domain_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='_type',
            field=models.IntegerField(choices=[(1, '除外'), (2, '必須')]),
        ),
    ]
