FROM nginx:1.17.4-alpine

RUN apk add --no-cache bash

COPY wait.sh /wait.sh

RUN chmod +x /wait.sh

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx_frontend.conf /etc/nginx/conf.d

#CMD ["/wait.sh", "nuxt:3000", "--", "nginx", "-g", "daemon off;"]