version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-northeast-1:381623038275:task-definition/yakuji-frontend:3"
        LoadBalancerInfo:
          ContainerName: "next"
          ContainerPort: 3000
        PlatformVersion: "LATEST"
        NetworkConfiguration:
            AwsvpcConfiguration:
              Subnets: ["subnet-0e49c8a5386593127"]
              SecurityGroups: ["sg-0970e52f075849eea"]
              AssignPublicIp: "DISABLED"