# Generated by Django 3.2.10 on 2022-01-18 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0002_alter_ng_keyword_condition_id'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ng_keywords',
        ),
        migrations.RemoveField(
            model_name='product_condition',
            name='ng_keyword',
        ),
        migrations.RemoveField(
            model_name='product_condition',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.product_condition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_condition',
            name='ng_keywords',
            field=models.ManyToManyField(to='conditions.NG_Keyword'),
        ),
    ]
