# Generated by Django 3.2.10 on 2022-01-18 08:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220118_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_condition',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
