# Generated by Django 3.2.10 on 2022-02-08 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmallGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.genre')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='small_genre',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.smallgenre'),
            preserve_default=False,
        ),
    ]
