# Generated by Django 3.2.10 on 2022-02-08 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20220208_1528'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='smallgenre',
            table='small_genre',
        ),
    ]
