# Generated by Django 3.2.10 on 2022-02-08 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_smallgenre_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SmallGenre',
            new_name='Small_Genre',
        ),
        migrations.RemoveField(
            model_name='product',
            name='genre',
        ),
    ]
