# Generated by Django 3.2.10 on 2022-02-09 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_image'),
        ('products', '0009_auto_20220208_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_condition',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
