# Generated by Django 3.2.10 on 2022-03-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_product_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_condition',
            name='check_target_period',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product_condition',
            name='period_unit',
            field=models.IntegerField(choices=[(1, 'days'), (2, 'months'), (3, 'years')], null=True),
        ),
    ]
