# Generated by Django 3.2.10 on 2022-01-18 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composite_Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'composite_keyword',
            },
        ),
        migrations.CreateModel(
            name='NG_Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ng_keyword',
            },
        ),
        migrations.CreateModel(
            name='NG_Keyword_Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_check_word_count', models.IntegerField()),
                ('back_check_word_count', models.IntegerField()),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('composite_keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conditions.composite_keyword')),
                ('ng_keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conditions.ng_keyword')),
            ],
            options={
                'db_table': 'ng_keyword_condition',
            },
        ),
        migrations.AddField(
            model_name='ng_keyword',
            name='composite_keywords',
            field=models.ManyToManyField(through='conditions.NG_Keyword_Condition', to='conditions.Composite_Keyword'),
        ),
    ]
