# Generated by Django 3.2.10 on 2022-01-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0002_alter_ng_keyword_condition_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ng_keyword_condition',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
