# Generated by Django 3.2.10 on 2022-01-19 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220119_1749'),
        ('conditions', '0003_alter_ng_keyword_condition_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ng_keyword',
            name='composite_keywords',
        ),
        migrations.AddField(
            model_name='ng_keyword_condition',
            name='product_condition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.product_condition'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ng_keyword',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
