# Generated by Django 3.2.10 on 2022-01-25 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220125_1136'),
        ('conditions', '0006_alter_composite_keyword_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ng_keyword_condition',
            name='product_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ng_keyword_conditions', to='products.product_condition'),
        ),
    ]
