# Generated by Django 3.2.10 on 2022-02-02 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0007_alter_ng_keyword_condition_product_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ng_keyword_condition',
            name='back_check_word_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ng_keyword_condition',
            name='composite_keyword',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conditions.composite_keyword'),
        ),
        migrations.AlterField(
            model_name='ng_keyword_condition',
            name='front_check_word_count',
            field=models.IntegerField(null=True),
        ),
    ]
