# Generated by Django 3.2.10 on 2022-02-09 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0008_auto_20220202_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='ng_keyword_condition',
            name='check_target_period',
            field=models.IntegerField(null=True),
        ),
    ]
