# Generated by Django 3.2.10 on 2022-02-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0009_ng_keyword_condition_check_target_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='ng_keyword_condition',
            name='period_unit',
            field=models.IntegerField(choices=[(1, 'days'), (2, 'months'), (3, 'years')], default=None),
            preserve_default=False,
        ),
    ]
