# Generated by Django 3.2.10 on 2022-02-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0010_ng_keyword_condition_period_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ng_keyword_condition',
            name='period_unit',
            field=models.IntegerField(choices=[(1, 'days'), (2, 'months'), (3, 'years')], null=True),
        ),
    ]
