# Generated by Django 3.2.10 on 2022-03-02 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0011_alter_ng_keyword_condition_period_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ng_keyword_condition',
            name='check_target_period',
        ),
        migrations.RemoveField(
            model_name='ng_keyword_condition',
            name='period_unit',
        ),
    ]
