# Generated by Django 3.2.10 on 2022-01-05 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True, unique=True)),
                ('emailVerified', models.DateTimeField(null=True)),
                ('image', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='VerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=200, unique=True)),
                ('expires', models.DateTimeField()),
            ],
            options={
                'db_table': 'verificationtoken',
                'unique_together': {('identifier', 'token')},
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('sessionToken', models.CharField(max_length=200, unique=True)),
                ('expires', models.DateTimeField()),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'session',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=200)),
                ('providerAccountId', models.CharField(max_length=200)),
                ('refresh_token', models.TextField(max_length=1000, null=True)),
                ('access_token', models.TextField(max_length=1000, null=True)),
                ('expires_at', models.IntegerField(null=True)),
                ('token_type', models.CharField(max_length=200, null=True)),
                ('scope', models.CharField(max_length=200, null=True)),
                ('id_token', models.TextField(max_length=1000, null=True)),
                ('session_state', models.CharField(max_length=200, null=True)),
                ('oauth_token_secret', models.CharField(max_length=200, null=True)),
                ('oauth_token', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'account',
                'unique_together': {('provider', 'providerAccountId')},
            },
        ),
    ]
