# Generated by Django 3.2.10 on 2022-02-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pg_id',
            field=models.IntegerField(null=True),
        ),
    ]
