# Generated by Django 3.2.10 on 2022-02-17 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_pg_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pg_id',
            new_name='mc_id',
        ),
    ]
